// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

import (
	"github.com/huantedness/autowire/example/msg"
)

// Injectors from wire.go:

func InitEventWithError() (*Event, error) {
	message := msg.NewMessage()
	event := NewEvent(message)
	return event, nil
}

func InitEvent() *Event {
	message := msg.NewMessage()
	event := NewEvent(message)
	return event
}

func InitEventWithDummyReturn() *Event {
	message := msg.NewMessage()
	event := NewEvent(message)
	return event
}

func InitEventWithWrongReturn() (*Event, func()) {
	message := msg.NewMessage()
	event := NewEvent(message)
	return event, func() {
	}
}

// wire.go:

type Event struct {
	Message *msg.Message
}

func NewEvent(message *msg.Message) *Event {
	return &Event{
		Message: message,
	}
}
